export const BAIRROS_LIST = [
  "Acaraú",
  "Aguas do Inga",
  "Aracaú",
  "Arariba",
  "Bairro Silop",
  "Bairro do Tenorio",
  "Barra Seca",
  "Barra Seca Praias Vermelha e Alto",
  "Barra da Lagoa",
  "Bela Vista",
  "Camburi",
  "Casanga",
  "Caçandoca",
  "Centro",
  "Centro (Picinguaba)",
  "Corcovado",
  "Estufa I",
  "Estufa II",
  "Figueira",
  "Flamengo Praias Ribeira e Sete Fortes",
  "Folha Seca",
  "Galhetas",
  "Horto",
  "Horto Florestal",
  "Ipiranguinha",
  "Itaguá",
  "Itamambuca",
  "Jardim Carolina",
  "Jardim Enseada",
  "Jardim Marisol",
  "Jardim Samambaia",
  "Jardim Santa Luzia",
  "Jardim Ubatuba",
  "Lagoinha",
  "Marafunda",
  "Mato Dentro",
  "Mato Dentro Carolina Trevo Samambá",
  "Monte Valerio",
  "Park Hills",
  "Pedreira",
  "Perequê-Açu",
  "Perequê-Mirim",
  "Picinguaba",
  "Ponta Aguda",
  "Ponta Grossa",
  "Praia Brava",
  "Praia Brava do Sul",
  "Praia Domingas Dias",
  "Praia Dura",
  "Praia Grande",
  "Praia Grande do Bonete Praia Deserto",
  "Praia Santa Rita",
  "Praia Vermelha do Centro",
  "Praia Vermelha do Sul",
  "Praia da Almada",
  "Praia da Barra",
  "Praia da Enseada",
  "Praia da Fazenda",
  "Praia da Fortaleza",
  "Praia das Toninhas",
  "Praia de Itaguá",
  "Praia de Maranduba",
  "Praia de Santa Rita",
  "Praia do Frade",
  "Praia do Félix",
  "Praia do Itamambuca",
  "Praia do Lazaro",
  "Praia do Perequê Mirim",
  "Praia do Pulso",
  "Praia do Puruba",
  "Praia do Sapê",
  "Praia do Sununga",
  "Promirim",
  "Prumirim",
  "Ressaca",
  "Rio Escuro",
  "Rio da Prata",
  "Saco da Ribeira",
  "Sape",
  "Sertao do Meio",
  "Sertao do Pereque Mirim",
  "Sertão da Quina",
  "Sertão do Ingá",
  "Sesmaria",
  "Silop",
  "Sumare",
  "Sumidouro",
  "Taquaral",
  "Tenório",
  "Ubatuba",
  "Ubatuba Country",
  "Ubatumirim",
  "Ubatumirin",
  "Umuarama",
  "Área Rural de Ubatuba"
];

export const PRAIAS_LIST = [
  "Almada",
  "Alto",
  "Barra",
  "Barra Seca",
  "Bicas",
  "Bonete",
  "Brava da Almada",
  "Brava da Fortaleza",
  "Brava da Itamambuca",
  "Brava do Camburi",
  "Brava do Perequê-Mirim (ou Lamberto)",
  "Brava do Sul",
  "Camburi",
  "Canto Itaipu",
  "Caçandoca",
  "Caçandoquinha",
  "Cedrinho ou Cedro",
  "Cedro ou Cedro do Sul",
  "Codó",
  "Costa",
  "Cruzeiro ou Iperoig",
  "Deserto",
  "Dionísia",
  "Domingas Dias",
  "Dura",
  "Engenho",
  "Enseada",
  "Estaleiro do Padre",
  "Fazenda",
  "Figueira",
  "Flamenguinho",
  "Flamengo",
  "Fora",
  "Fortaleza",
  "Félix",
  "Galhetas",
  "Gerônimo ou Boa Vista",
  "Godói",
  "Grande do Bonete",
  "Itaguá",
  "Itamambuca",
  "Itapecerica",
  "Justa",
  "Lagoa",
  "Lagoinha",
  "Lamberto (ou Brava do Perequê-Mirim)",
  "Lanço da Cavala",
  "Lázaro",
  "Leste do Tenório",
  "Mansinho",
  "Manso",
  "Maranduba",
  "Matinha",
  "Oeste do Tenório",
  "Palmas",
  "Pedra Miúda (ou Domingas Dias Pequena)",
  "Perequê-Açu",
  "Perequê-Mirim",
  "Perez",
  "Picinguaba",
  "Ponta Aguda",
  "Ponta Grossa",
  "Prainha do Cais",
  "Prainha do Deserto",
  "Prainha do Engenho",
  "Prainha do Félix",
  "Prainha do Lázaro",
  "Prainha do Tenório",
  "Promirim (ou Prumirim)",
  "Pulso",
  "Puruba",
  "Quina (Sertão da Quina)",
  "Ribeira",
  "Saco da Mãe Maria",
  "Saco da Ribeira",
  "Saco das Bananas",
  "Saco do Cedro",
  "Santa Rita",
  "Sapê",
  "Sete Fontes",
  "Simão",
  "Sununga",
  "Tapera",
  "Tenório",
  "Toninhas",
  "Ubatumirim",
  "Vermelha do Centro",
  "Vermelha do Norte",
  "Vermelha do Sul",
  "Vila (Picinguaba)"
];
